### ISSUE TITLE
https://github.com/eclipse-tm4e/tm4e/wiki/ links broken

### ISSUE THREAD

**Issue by vogella** [eclipse-tm4e/tm4e#832]
See [Core](https://github.com/eclipse-tm4e/tm4e/wiki/Core) section for more information and  See [UI](https://github.com/eclipse-tm4e/tm4e/wiki/UI) are not working. 

Not sure if the wiki was retired.

**Comment by sebthom** [comment]
Thanks for reporting! Fixed by https://github.com/eclipse-tm4e/.eclipsefdn/commit/73eef83e0f9fb8abcc5380188760af798d0f023b
