### ISSUE TITLE
Adding Asciidoc grammar

### ISSUE THREAD

**Issue by vogella** [eclipse-tm4e/tm4e#843]
Based on https://asciidoctor.zulipchat.com/#narrow/channel/279642-users/topic/Is.20there.20a.20TextMate.20grammer.20available.20for.20Asciidoc.3F I learned about https://github.com/asciidoctor/asciidoctor-vscode/blob/master/syntaxes/Asciidoctor.json provides  a grammer for Asciidoc in Vscode.

Would you accept PR to add this to the TM4E language pack? I would happy to give it a try, I'm currently building my own small Asciidoc editor in Eclipse and it would nice if that could be based on TM4E.

**Comment by sebthom** [comment]
I’m opposed to including and maintaining separate grammars that aren’t part of the upstream VS Code repository into the language pack, given the slow and tedious IP review process.

Instead, I suggest we add the grammar to https://github.com/sebthom/extra-syntax-highlighting-eclipse-plugin, where upstream grammar updates can be integrated automatically.
